# Generated by Django 4.1.7 on 2023-03-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ScheduleTitle', models.CharField(blank='', max_length=150, null=True)),
                ('ScheduleType', models.CharField(blank='', max_length=150, null=True)),
                ('participant', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Idol-Schedules',
            },
        ),
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idol_group', models.CharField(blank=True, choices=[('GirlGroup', 'GirlGroup'), ('BoyGroup', 'BoyGroup')], max_length=30, null=True)),
                ('idol_solo', models.CharField(blank=True, choices=[('GirlSolo', 'GirlSolo'), ('BoySolo', 'BoySolo')], max_length=30, null=True)),
                ('idol_name', models.CharField(max_length=7)),
                ('idol_profile', models.URLField(blank=True, max_length=10000)),
                ('idol_anniv', models.DateField()),
                ('idol_birthday', models.DateField()),
                ('idol_gender', models.CharField(choices=[('Women', 'Women'), ('Man', 'Man')], max_length=5)),
                ('idol_schedule', models.ManyToManyField(blank=True, null=True, related_name='idols', to='idols.schedule')),
            ],
            options={
                'verbose_name_plural': 'Our_Idols',
            },
        ),
    ]
