# Generated by Django 4.1.7 on 2023-03-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='participant',
            field=models.ManyToManyField(blank=True, max_length=150, related_name='schedules', to='idols.idol'),
        ),
    ]
