# Generated by Django 4.1.7 on 2023-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='idol_profile',
            field=models.URLField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='idol',
            name='idol_schedule',
            field=models.ManyToManyField(related_name='idols', to='idols.schedule'),
        ),
    ]
