# Generated by Django 4.1.7 on 2023-03-07 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('idols', '0002_alter_schedule_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='idol_schedules',
            field=models.ManyToManyField(blank=True, related_name='idols', to='idols.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ScheduleType',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='categories.category'),
        ),
    ]
