# Generated by Django 4.1.7 on 2023-03-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_alter_idol_idol_profile_alter_idol_idol_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='idol',
            name='idol_groupName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='idol',
            name='idol_profile',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
