# Generated by Django 4.1.7 on 2023-03-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_idol_idol_groupname_alter_idol_idol_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='idol_gender',
            field=models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man')], max_length=5),
        ),
    ]
