# Generated by Django 4.1.7 on 2023-03-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0004_alter_idol_idol_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='idol_groupName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
