# Generated by Django 4.1.7 on 2023-03-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0005_schedule_idol_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='idol_schedule',
            field=models.ManyToManyField(blank=True, related_name='idols', to='idols.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ScheduleType',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
