# Generated by Django 4.1.7 on 2023-03-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalendar',
            name='content',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
